artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  classification_source_URL: "https://drive.google.com/file/d/1SA6o6zmGJ1bCpGIP_Aa0Cw-Hal4zSM15/view?usp=sharing"
  detection_source_URL: "https://drive.google.com/file/d/174ngDhD-lKLsDWZXR-_OuX-MmJf6ZpSR/view?usp=sharing"
  classification_local_data_file: artifacts/data_ingestion/classification_data.zip
  detection_local_data_file: artifacts/data_ingestion/detection_data.zip
  classification_unzip_dir: artifacts/data_ingestion
  detection_unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  classification_data_dir: artifacts/data_ingestion/classification_dataset
  detection_data_dir: artifacts/data_ingestion/object_detection_Dataset
  validation_status_file: artifacts/data_validation/status.txt

model_trainer:
  root_dir: artifacts/model_trainer
  classification_trained_model_path: artifacts/model_trainer/classification_model.h5
  detection_trained_model_path: artifacts/model_trainer/detection_model.pt
  classification_training_data: artifacts/data_ingestion/classification_dataset
  detection_training_data: artifacts/data_ingestion/object_detection_Dataset